### ISSUE TITLE
when i vapor build in container, the error occur "backgroundExecute(code: 1,...."

### ISSUE THREAD

**Issue by wanqingrongruo** [vapor/vapor#2135]
Hi, 
I have a problem, i need help...please

### My Problem
```
➜  vapor-env git:(master) ✗ docker exec -it vapor-env_vapor_1 bash
root@00e86c1607ae:/var/www/HelloWorld# vapor build
No .build folder, fetch may take a while...
Fetching Dependencies [ •                       ]
Error: backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\nerror: root manifest not found\n", output: "")
root@00e86c1607ae:/var/www/HelloWorld#
```

### Steps to reproduce

I use docker-compose to deploy nginx and vapor container. Then, In vapor container, i use `vapor build` to create a project, but i failed.
The .env:
```
HOST_ROOT=./vapor/HelloWorld
CONTAINER_ROOT=/var/www/HelloWorld

HOST_HTTP_PORT=80

CURRENT_NGINX_IMG=boxue/nginx:0.1.0
CURRENT_VAPOR_IMG=boxue/vapor:0.1.1
```
The docker-compose.yml:
```
version: "3.6"

services:
    vapor:
        build:
            context: ./vapor
        image: ${CURRENT_VAPOR_IMG}
        ports:
            - 8080:8080
        volumes:
            - ${HOST_ROOT}:${CONTAINER_ROOT}
        working_dir: ${CONTAINER_ROOT}
        tty: true
        entrypoint: bash
        networks:
            - bx-net

    nginx:
        build:
            context: ./nginx
        image: ${CURRENT_NGINX_IMG}
        ports:
            - ${HOST_HTTP_PORT}:80
        volumes:
            - ${HOST_ROOT}:${CONTAINER_ROOT}
        networks:
            - bx-net

networks:
    bx-net:
        driver: bridge
```

I reflect './vapor/HelloWorld' to `/var/www/HelloWorld`.
But in `/var/www/HelloWorld`: I run `vapor build`, the error appeared.
in `./vapor/HelloWorld`, it works.

### Expected behavior

It should create a vapor project successfully.

### Actual behavior

```
➜  vapor-env git:(master) ✗ docker exec -it vapor-env_vapor_1 bash
root@00e86c1607ae:/var/www/HelloWorld# vapor build
No .build folder, fetch may take a while...
Fetching Dependencies [ •                       ]
Error: backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\nerror: root manifest not found\n", output: "")
root@00e86c1607ae:/var/www/HelloWorld#
```

### Environment
* Vapor Framework version: I failed to create project
* Vapor Toolbox version: 3.1.10
* OS version: macOS Catalina 10.15.1

### Thx
I am looking forward to your reply, thx.
