### ISSUE TITLE
duplicate symbol __TMRbBp (Xcode 8.1)

### ISSUE THREAD

**Issue by gperdomor** [vapor/vapor#782]
I have problems with travis build, when OS X image is xcode8.1 (which use swift 3.0.1)

```
Linking ./.build/release/App
duplicate symbol __TMRbBp in:
    /Users/travis/build/gperdomor/sygnaler/.build/release/Fluent.build/SQL/GeneralSQLSerializer.swift.o
    /Users/travis/build/gperdomor/sygnaler/.build/release/SocksCore.build/TCPSocket.swift.o
ld: 1 duplicate symbol for architecture x86_64
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/travis/build/gperdomor/sygnaler/.build/release.yaml
❌  Build for release failed
```

this is my travis.yaml

```yaml
language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: VERSION=3.0
    - os: osx
      osx_image: xcode8.1
      env: VERSION=3.0.1
    - os: osx
      osx_image: xcode8.2
      env: VERSION=3.0.2
    - os: linux
      sudo: required
      dist: trusty
      env: VERSION=3.0
    - os: linux
      sudo: required
      dist: trusty
      env: VERSION=3.0.1
    - os: linux
      sudo: required
      dist: trusty
      env: VERSION=3.0.2

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install mysql;
    else
      wget https://dev.mysql.com/get/mysql-apt-config_0.8.1-1_all.deb;
      sudo dpkg -i mysql-apt-config_0.8.1-1_all.deb;
      sudo apt-get -qq update;
      sudo apt-get install -y mysql-server libmysqlclient-dev;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then BUILD_ARGS="-Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib"; fi

script:
  - BUILD_ARGS=$BUILD_ARGS ./travis/ci.sh
```

and my ci.sh

```bash
#!/usr/bin/env bash

echo "Swift $VERSION Continuous Integration";

# Determine OS
UNAME=`uname`;
if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
else
    if [[ $UNAME == "Linux" ]];
    then
        UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
        if [[ $UBUNTU_RELEASE == *"15.10"* ]];
        then
            OS="ubuntu1510";
        else
            OS="ubuntu1404";
        fi
    else
        echo "Unsupported Operating System: $UNAME";
    fi
fi
echo "🖥 Operating System: $OS";

if [[ $OS != "macos" ]];
then
    echo "📚 Installing Dependencies"
    sudo apt-get install -y clang libicu-dev uuid-dev

    echo "🐦 Installing Swift";
    if [[ $OS == "ubuntu1510" ]];
    then
        SWIFTFILE="swift-$VERSION-RELEASE-ubuntu15.10";
    else
        SWIFTFILE="swift-$VERSION-RELEASE-ubuntu14.04";
    fi
    wget https://swift.org/builds/swift-$VERSION-release/$OS/swift-$VERSION-RELEASE/$SWIFTFILE.tar.gz
    tar -zxf $SWIFTFILE.tar.gz
    export PATH=$PWD/$SWIFTFILE/usr/bin:"${PATH}"
fi

echo "📅 Version: `swift --version`";

echo "🚀 Building";
swift build $BUILD_ARGS
if [[ $? != 0 ]];
then
    echo "❌  Build failed";
    exit 1;
fi

echo "💼 Building Release";
swift build -c release $BUILD_ARGS
if [[ $? != 0 ]];
then
    echo "❌  Build for release failed";
    exit 1;
fi

#echo "🔎 Testing";

#swift test $BUILD_ARGS
#if [[ $? != 0 ]];
#then
#    echo "❌ Tests failed";
#    exit 1;
#fi

echo "✅ Done"

```
